### ISSUE TITLE
[Transcribe Endpoint Error] - Wrong Transcribe Endpoint definition in class KVSTranscribeStreamingLambda

### ISSUE THREAD

**Issue by nikosheng** [amazon-connect/ai-powered-speech-analytics-for-amazon-connect#17]
Hi,

I deployed the stack in ap-southeast-1 and us-east-1 respectively and found out that in ap-southeast-1, KVSTranscribeStreamingLambda is failed to run due to the wrong endpoint address 
`"https://transcribestreaming." + TRANSCRIBE_REGION.getName() + ".amazonaws.com"`

According to the [official doc](https://docs.aws.amazon.com/zh_cn/general/latest/gr/transcribe.html), the endpoint should be defined as below 

```
private static final String TRANSCRIBE_ENDPOINT = "https://transcribe." + TRANSCRIBE_REGION.getName() + ".amazonaws.com";
```

Please kindly help to address it or correct me if any misunderstanding.

Thanks

**Comment by efh365** [comment]
Hi, 

The transcribe service we are using in this solution is Transcribe Streaming, not just Transcribe. Currently Transcribe Streaming is not available in ap-southeast-1 (Singapore), which is why it is not working. You can see the available regions here: https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/ (Transcribe Streaming is marked after the table in italics)
