### ISSUE TITLE
How can I get Agent Transcript on Front End

### ISSUE THREAD

**Issue by aman-appcino** [amazon-connect/ai-powered-speech-analytics-for-amazon-connect#19]
I am able to save the transcript to DDB but not able to get it on frontend.
I tried to make a clone of lambda funtion ( Ai-powered-speech-analyti-wsrealtimetranscribeOnDD ) and set the trigger on tocustomer DDB but not able to get the data on frontend.
I think DDB scan method returning empty array instead of transcript .
can you help me with the same. what I need to do and get the agent transcript on front end.

**Comment by efh365** [comment]
Hi @aman-appcino. In order to get the transcript to the frontend, you need to setup a new websocket connection or modify the existing one. This is the lambda function that is triggered when a new transcript is inserted into the DDB: https://github.com/amazon-connect/ai-powered-speech-analytics-for-amazon-connect/blob/master/source/ws_realtime_transcribe_OnDDBInsert/index.js

You can see that it sends the transcript to the API GW websocket connection that is established.

**Comment by aman-appcino** [comment]
Hi @efh365  ,
Thank you for reply .
I have resolved the issue by adding trigger on table.
