### ISSUE TITLE
lambda.invokeAsync depracated

### ISSUE THREAD

**Issue by czhao028** [amazon-connect/ai-powered-speech-analytics-for-amazon-connect#2]
Although it seems like this code is fairly recently built, the Java SDK says that lambda.invokeAsync is deprecated, which appears in index.js of kvs_trigger. If we're trying to deploy this is a lambda function ourselves (with a few modifications), should we swap out the invokeAsync with invoke(request)? Is there a different version that ran with the CloudFormation template?

**Comment by czhao028** [comment]
CloudFormation template mentioned is deployment/AI-powered-speech-analytics-for-amazon-connect.template

**Comment by efh365** [comment]
It looks like invokeAsync() is deprecated in the java sdk, but not in the js sdk. Since this is used in the kvs_trigger function, which is js, it should be ok to use. That is what we have used throughout our development and testing.

js: https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Lambda.html#invokeAsync-property
java: https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/lambda/AWSLambda.html#invokeAsync-com.amazonaws.services.lambda.model.InvokeAsyncRequest-
