### ISSUE TITLE
Error on UI when connecting to connect

### ISSUE THREAD

**Issue by mahajanroopali** [amazon-connect/ai-powered-speech-analytics-for-amazon-connect#38]
When I launch the UI, For the agent assist section, I get below error message in browser 

"To protect your security, ab2-roopali-connect-demo.awsapps.com will not allow Firefox to display the page if another site has embedded it. "
On opening in new browser, I get error -
"Access Error
This application has not been enabled for your directory. Please contact your Administrator for more details."

In developer tools, I can see below error - 
[HTTP/1.1 403 Forbidden 0ms]
The loading of “https://*******/connect/login” in a frame is denied by “X-Frame-Options“ directive set to “SAMEORIGIN“.

I will appreciate if you can help with this error

**Comment by virtualgill** [comment]
Hi @mahajanroopali 

Thanks for raising this. The solution currently only supports the older Amazon Connect url format. It’s on the team’s roadmap to provide support for both. For now in order to use this with a newer Amazon Connect instance, you can update the loginURL and ccpURL variables in agentAssist.html.

The agentAssist.html file can be found in the repo at: [https://github.com/amazon-connect/ai-powered-speech-analytics-for-amazon-connect/blob/main/source/web_site/agentAssist.html](https://github.com/amazon-connect/ai-powered-speech-analytics-for-amazon-connect/blob/main/source/web_site/agentAssist.html)

The deployed location of this is s3://{YOUR_BUCKET_NAME}/CCP/agentAssist.html
The lines that need updated are 405/406
```
var loginURL = https://${instanceAlias}.[awsapps.com/connect/login](http://awsapps.com/connect/login);
var ccpURL = https://${alias}.[awsapps.com/connect/ccp-v2/softphone](http://awsapps.com/connect/ccp-v2/softphone);
```
To use with a new instance they need changed to :
```
var loginURL = https://${instanceAlias}.my.connect.aws/login;
var ccpURL = https://${alias}.my.connect.aws/ccp-v2/softphone;
```

You can manually overwrite this file in the S3 bucket, but be sure to either wait for the Amazon CloudFront cache to clear or invalidate it yourself (instructions [here](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/Invalidation.html)).

If you run into any other issues it’s worth also updating to the latest version of the Amazon Connect Streams API from https://www.npmjs.com/package/amazon-connect-streams (by replacing the one [here](https://github.com/amazon-connect/ai-powered-speech-analytics-for-amazon-connect/blob/main/source/web_site/js/connect-streams.js)).

**Comment by mahajanroopali** [comment]
Thank you. The fix  worked and the UI loads seamlessly now.
